/**
 * Active-route variants (Phase 14b).
 *
 * OneMap returns exactly one walk/cycle path per origin→destination, so the
 * Fastest / Most-sheltered / PCN-scenic options are generated by routing
 * through a via-point — the nearest point on the target network (PCN or OSM
 * covered walkways) to the direct route's midpoint — and kept only when the
 * detour genuinely improves that metric. Multi-stop journeys apply the same
 * treatment per segment and stitch.
 */
import { oneMapActiveRoute } from "./onemap.js";
import {
  SegmentGrid,
  decodePolyline5,
  encodePolyline5,
  routeCoverage,
  comfortLabel,
  activeKcal,
  planarMeters,
  type Pt,
} from "./activeNetwork.js";
import type {
  ActiveMode,
  ActiveModeRoutes,
  ActiveVariant,
  ActiveVariantKind,
  ActiveSegment,
  LatLng,
} from "../../shared/types.js";

interface RawRoute {
  polyline: string;
  distanceM: number;
  durationS: number;
}

// Keep a via-detour only when it clearly earns its extra distance.
const PCN_SKIP_PCT = 75; // direct route already lives on the network
const SHELTER_SKIP_PCT = 60;
const MIN_GAIN_PTS = 10; // detour must improve the metric by at least this
const MAX_DETOUR_FACTOR = 2.2; // and not more than ~2.2× the direct distance
const PCN_VIA_RADIUS_M = 1500;
const SHELTER_VIA_RADIUS_M = 1200;

/** Point along a path at half its cumulative length. */
export function pathMidpoint(pts: Pt[]): Pt {
  if (pts.length === 1) return pts[0];
  let total = 0;
  for (let i = 1; i < pts.length; i++)
    total += planarMeters(pts[i - 1], pts[i]);
  let acc = 0;
  for (let i = 1; i < pts.length; i++) {
    const d = planarMeters(pts[i - 1], pts[i]);
    if (acc + d >= total / 2) {
      const t = d === 0 ? 0 : (total / 2 - acc) / d;
      return {
        lat: pts[i - 1].lat + (pts[i].lat - pts[i - 1].lat) * t,
        lng: pts[i - 1].lng + (pts[i].lng - pts[i - 1].lng) * t,
      };
    }
    acc += d;
  }
  return pts[pts.length - 1];
}

/** Join two consecutive raw routes into one (decode, concat, re-encode). */
export function stitchRoutes(a: RawRoute, b: RawRoute): RawRoute {
  const pts = [...decodePolyline5(a.polyline), ...decodePolyline5(b.polyline)];
  return {
    polyline: encodePolyline5(pts),
    distanceM: a.distanceM + b.distanceM,
    durationS: a.durationS + b.durationS,
  };
}

function pctOf(route: RawRoute, grid: SegmentGrid | null): number {
  if (!grid) return 0;
  return routeCoverage(decodePolyline5(route.polyline), grid).pct;
}

/**
 * Try a via-point detour that pulls the route onto `grid`'s network.
 * Returns null when the direct route already qualifies, no via exists, the
 * detour is absurd, or it doesn't meaningfully improve the metric.
 */
async function viaVariant(
  mode: ActiveMode,
  start: LatLng,
  end: LatLng,
  direct: RawRoute,
  directPct: number,
  grid: SegmentGrid | null,
  opts: { skipPct: number; radiusM: number },
): Promise<{ route: RawRoute; pct: number } | null> {
  if (!grid || directPct >= opts.skipPct) return null;
  const mid = pathMidpoint(decodePolyline5(direct.polyline));
  const via = grid.nearestPoint(mid, opts.radiusM);
  if (!via || planarMeters(via, mid) < 60) return null; // already passes it
  const [r1, r2] = await Promise.all([
    oneMapActiveRoute(start, via, mode).catch(() => null),
    oneMapActiveRoute(via, end, mode).catch(() => null),
  ]);
  if (!r1 || !r2) return null;
  const stitched = stitchRoutes(r1, r2);
  if (stitched.distanceM > direct.distanceM * MAX_DETOUR_FACTOR) return null;
  const pct = pctOf(stitched, grid);
  if (pct < directPct + MIN_GAIN_PTS) return null;
  return { route: stitched, pct };
}

interface SegmentPlan {
  direct: RawRoute;
  pcn: RawRoute | null;
  shelter: RawRoute | null;
}

async function planSegment(
  mode: ActiveMode,
  start: LatLng,
  end: LatLng,
  pcnGrid: SegmentGrid | null,
  shelterGrid: SegmentGrid | null,
): Promise<SegmentPlan | null> {
  const direct = await oneMapActiveRoute(start, end, mode).catch(() => null);
  if (!direct) return null;
  const [pcn, shelter] = await Promise.all([
    viaVariant(mode, start, end, direct, pctOf(direct, pcnGrid), pcnGrid, {
      skipPct: PCN_SKIP_PCT,
      radiusM: PCN_VIA_RADIUS_M,
    }),
    mode === "walk"
      ? viaVariant(
          mode,
          start,
          end,
          direct,
          pctOf(direct, shelterGrid),
          shelterGrid,
          { skipPct: SHELTER_SKIP_PCT, radiusM: SHELTER_VIA_RADIUS_M },
        )
      : Promise.resolve(null),
  ]);
  return { direct, pcn: pcn?.route ?? null, shelter: shelter?.route ?? null };
}

/** Compose one journey-level variant from a per-segment route choice. */
function compose(
  kind: ActiveVariantKind,
  mode: ActiveMode,
  routes: RawRoute[],
  pcnGrid: SegmentGrid | null,
  shelterGrid: SegmentGrid | null,
): ActiveVariant {
  const coords = routes.flatMap((r) => decodePolyline5(r.polyline));
  const distanceM = routes.reduce((s, r) => s + r.distanceM, 0);
  const durationS = routes.reduce((s, r) => s + r.durationS, 0);
  const pcnPct = pcnGrid ? routeCoverage(coords, pcnGrid).pct : 0;
  const shelterPct =
    mode === "walk" && shelterGrid
      ? routeCoverage(coords, shelterGrid).pct
      : undefined;
  const segments: ActiveSegment[] = routes.map((r) => ({
    polyline: r.polyline,
    distanceM: r.distanceM,
    durationS: r.durationS,
  }));
  return {
    kind,
    durationS,
    distanceM,
    kcal: activeKcal(mode, distanceM),
    pcnPct,
    shelterPct,
    comfort: comfortLabel(pcnPct, mode),
    segments,
  };
}

const sameRoutes = (a: ActiveVariant, b: ActiveVariant) =>
  a.segments.length === b.segments.length &&
  a.segments.every((s, i) => s.polyline === b.segments[i].polyline);

/**
 * Build the ordered variant list for one mode across all stops.
 * Walk: fastest → most sheltered → PCN scenic. Cycle: fastest → PCN scenic.
 * Flavours whose best path coincides with an earlier option merge into its
 * `also` badges instead of repeating a card.
 */
export async function buildActiveMode(
  mode: ActiveMode,
  points: LatLng[],
  pcnGrid: SegmentGrid | null,
  shelterGrid: SegmentGrid | null,
): Promise<ActiveModeRoutes | null> {
  const plans = await Promise.all(
    points
      .slice(0, -1)
      .map((p, i) => planSegment(mode, p, points[i + 1], pcnGrid, shelterGrid)),
  );
  if (plans.some((p) => p === null)) return null;
  const segs = plans as SegmentPlan[];

  const fastest = compose(
    "fastest",
    mode,
    segs.map((s) => s.direct),
    pcnGrid,
    shelterGrid,
  );

  // "Sheltered" is only offered when the OSM covered-walkway layer loaded —
  // no data means no claim, not a hollow badge. Offered for cycle too (a
  // rain-covered alternative), so both foot modes surface up to 3 options; the
  // merge below drops it when it coincides with the fastest/PCN route.
  const kinds: ActiveVariantKind[] = shelterGrid
    ? ["sheltered", "pcn"]
    : ["pcn"];
  const variants: ActiveVariant[] = [fastest];

  for (const kind of kinds) {
    const anyImproved = segs.some((s) =>
      kind === "pcn" ? s.pcn : s.shelter,
    );
    if (!anyImproved) {
      // No worthwhile detour exists. Badge the fastest route with this
      // flavour ONLY if it genuinely qualifies on the metric — a 31%-PCN
      // route must not wear a "PCN scenic" badge just because we couldn't
      // beat it.
      const qualifies =
        kind === "pcn"
          ? fastest.pcnPct >= PCN_SKIP_PCT
          : (fastest.shelterPct ?? 0) >= SHELTER_SKIP_PCT;
      if (qualifies) fastest.also = [...(fastest.also ?? []), kind];
      continue;
    }
    const v = compose(
      kind,
      mode,
      segs.map((s) => (kind === "pcn" ? (s.pcn ?? s.direct) : (s.shelter ?? s.direct))),
      pcnGrid,
      shelterGrid,
    );
    const twin = variants.find((x) => sameRoutes(x, v));
    if (twin) twin.also = [...(twin.also ?? []), kind];
    else variants.push(v);
  }

  // Display order: fastest, sheltered, pcn (either foot mode may omit a flavour
  // that merged into another or had no worthwhile detour).
  const order: Record<ActiveVariantKind, number> = {
    fastest: 0,
    sheltered: 1,
    pcn: 2,
  };
  variants.sort((a, b) => order[a.kind] - order[b.kind]);
  return { variants };
}
